### ISSUE TITLE
Header fixé

### ISSUE THREAD

**Issue by Shaktohh** [tonnerre33/jeedom_FB33_responsive#2]
Bonjour,
Penses-tu pouvoir fixer la barre de menu lorsqu'on défile la barre ?
J'ai vu une possibilité bootstrap : data-spy="affix" mais je ne susi pas parvenu à la mettre en oeuvre.
Cordialement,

**Comment by tonnerre33** [comment]
Salut,
Très bonne idée, je n'y avais pas pensé. J'y ai un peu travaillé dessus ce soir, ca à l'air d'être bon mais je testerai ca plus en détail demain soir sur différents supports ;)

**Comment by Shaktohh** [comment]
Hello,
Je pense que ce serait pas mal également d'intégrer dans chaque cadre un ascenseur verticale quand le contenu dépasse la hauteur du cadre définie quand celle-ci est forcée ? (un petit overflow-y:scroll;)
Ca permettrait d'avoir une solution pour les cadres qui n'ont pas la même height. (j'aime bien quand c'est droit et aligné 👍 )

**Comment by tonnerre33** [comment]
Salut,
Normalement c'est bon pour la fixation du menu ;) Pour l'ascenseur verticale je regarde ca plus tard car la barre qui s'affiche à coté de la div c'est pas très joli tout ca. Il faut que je regarde si on peut la masquer ;)

**Comment by Shaktohh** [comment]
Je vais test ça.
Pour le custom de l'ascenseur il y a des solutions jquery à la rigueur pour faire du joli custom
http://www.magazineduwebdesign.com/plugin-jquery-scrollbar/

Je pense que le mieux serait de pouvoir l'afficher (pour les ordinateurs portables sans souris par exemple) ou non (pour du tactile)

Edit : C'est ok pour le menu fixe :) 
Merci !

**Comment by tonnerre33** [comment]
Commit effectué, tu me diras si c'est ce que tu recherchais ;)
ca fonctionne chez moi mais je ne suis pas certain de m'en servir, du coup je veux bien voir ton résultat :)

**Comment by Shaktohh** [comment]
Super exactement ce que je cherchais !
Ma div météo prenait trop de place entre la météo et les précipitations mais je voulais avoir les 2 pour scroll si besoin.

Un petit screen de mon Dashboard en cours de construction
https://img4.hostingpics.net/pics/770850design.png

**Comment by tonnerre33** [comment]
Trop bien ce que tu as déjà fait !! Pour l'état de la maison ça m’intéresse , tu gères ça comment ?
Si c'est en nuit ca remplace met NUIT sur la gauche à la place de "Présent" ou est-ce que tu peux être présent et en nuit ?
Tu gères ça avec des virtuels ?

**Comment by Shaktohh** [comment]
Nan je gère ca avec un seul virtuel et des commandes associées.
J'aurais pû faire des modes pouvant aller ensemble mais je pense mettre des alarmes quand je vais dormir donc je préfère changer manuellement l'état de la maison, histoire que si je sorte pour une raison x ou y et que je ne suis pas couché, ca sonne pas pour rien.

**Comment by tonnerre33** [comment]
Tu pourras m'envoyer un screen du code de ton virtuel ?

**Comment by Shaktohh** [comment]
https://img4.hostingpics.net/pics/946908virtuel.png

Et le widget pour les boutons :
https://mensuel.framapad.org/p/4f5GYUCao6

Le widget pour l'état à gauche : 
https://mensuel.framapad.org/p/vMGuMRqwzd

**Comment by Shaktohh** [comment]
code ne passe pas sur github

**Comment by tonnerre33** [comment]
Pas de soucis. Merci pour le partage.

**Comment by tonnerre33** [comment]
Ok merci pour les codes ca va me faire gagner du temps :) 
pour l'histoire des précipitations tu utilises le plugin Vigilance Météo ?

**Comment by Shaktohh** [comment]
Oui c'est ça.

**Comment by tonnerre33** [comment]
Je me permet de poster les codes ici car ils vont s'effacer dans 30 jours  :wink:
Pour poster un code sur github il faut utiliser ``` sur la première et dernière ligne 
et pour activer la reconnaissance syntaxique c'est les trois petits trucs avec le code attache ``html (je n'en ai mis que deux sinon ca s'affiche pas)


# widget pour les boutons :
```html
<div style="width:150px;min-height:25px;margin: 3px 0 3px 0;background-color: rgba(0,0,0,0.3);border-radius: 25px;padding-top:1px;float:right;" class="cmd tooltips cmd-widget cursor" data-type="action" data-subtype="string" data-cmd_id="#id#">
      <div class="iconState#id#" style="float:left;">
            <img src="" alt ="house" style="width:18px;height:18px;margin: 0px 10px 0px 30px;" />
            <span class='cmdName action' style="font-weight: bold;font-size : 12px; padding-left: 6px;">#name_display#</span>    
    </div>
  
    <script>
    switch("#name#"){
      case "Présent" :
         $('.iconState#id# img').attr("src", "montheme/icones/home-3-24.png");
        break; 
      case "Absent" :
         $('.iconState#id# img').attr("src", "montheme/icones/running-24.png");
        break; 
      case "Vacances" :
         $('.iconState#id# img').attr("src", "montheme/icones/beach-24.png");
        break;
      case "Nuit" :
         $('.iconState#id# img').attr("src", "montheme/icones/moon-4-24.png");
        break; 
      case "Travail" :
         $('.iconState#id# img').attr("src", "montheme/icones/Student-Laptop-24.png");
        break; 
    }
        $('.cmd[data-cmd_id=#id#] .action').on('click', function () {jeedom.cmd.execute({id: '#id#'});});
    </script>
</div>
```
# Widget pour l'état à gauche :
```html
<div class="cmd #history# tooltips" data-type="info" data-subtype="string" data-cmd_id="#id#" title="#collectDate#" style="float:left;padding-bottom: 30px;"> 
  <div class="divfather#id#">
    <span style="font-size:20px; font-weight: bold;">
         <br />#state# <br />
        <img src="" alt="etat" style="margin-top: 10px;"/>
    </span>
  </div>
</div> 

    <script>
    switch("#state#"){
      case "Présent" :
         $('.divfather#id# img').attr("src", "montheme/icones/home-3-48.png");
        break; 
      case "Absent" :
         $('.divfather#id# img').attr("src", "montheme/icones/running-48.png");
        break; 
      case "Vacances" :
         $('.divfather#id# img').attr("src", "montheme/icones/beach-48.png");
        break;
      case "Nuit" :
         $('.divfather#id# img').attr("src", "montheme/icones/moon-4-48.png");
        break; 
      case "Travail" :
         $('.divfather#id# img').attr("src", "montheme/icones/Student-Laptop-48.png");
        break; 
    }
    </script>  
```
